include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_redundant_argument_values
    - unnecessary_string_interpolations
    - unnecessary_brace_in_string_interps
    - prefer_single_quotes

    #
    - prefer_final_fields
    - use_key_in_widget_constructors
    - sort_child_properties_last
    - use_build_context_synchronously
    - no_leading_underscores_for_local_identifiers
    - sized_box_for_whitespace

    - camel_case_types
    - camel_case_extensions
    - non_constant_identifier_names
    - library_prefixes
    - package_api_docs
